---
- name: Set up ngingx container
  hosts: 127.0.0.1
  gather_facts: no
  connection: local



  tasks:

    - name: Make directory for debian tree
      file: path="{{ playbook_dir }}/debian-tree/" state=directory owner=root group=root
      sudo: true


    # Create a Debian image from scratch
    # May take a while to download packages
    - name: debootstrap
      command: debootstrap
               --arch=amd64
               unstable
               "{{ playbook_dir }}/debian-tree/"
      sudo: true

    # Boot the machine stored at debian-tree and run /bin/true
    # Will exit immediately
    # To verify this, you can switch /bin/true to /bin/false
    # and watch the command fail
    - name: Spawn machine
      command: systemd-nspawn -D debian-tree/ /bin/true
      sudo: true
